FROM python:3.6.6-slim-stretch

COPY requirements.txt .
RUN pip install --upgrade -r requirements.txt

COPY 020_api 020_api

ENTRYPOINT [ "python3.6", "/020_api/flask_canary.py" ]

# sudo docker build --no-cache -t canary -f Dockerfile_canary .
# sudo docker run -p 5001:5001 canary